// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_backtest
NumericVector cpp_backtest(NumericVector asset_returns, NumericVector signals);
RcppExport SEXP _dataapp_cpp_backtest(SEXP asset_returnsSEXP, SEXP signalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type asset_returns(asset_returnsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type signals(signalsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_backtest(asset_returns, signals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dataapp_cpp_backtest", (DL_FUNC) &_dataapp_cpp_backtest, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_dataapp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
