# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Backtest Engine in C++
#'
#' Iterates through a vector of returns and trading signals to compute the cumulative equity line.
#'
#' @param asset_returns A numeric vector of the daily percentage returns of the asset.
#' @param signals A numeric vector of signals (-1, 0, 1). Signals should theoretically be lagged by 1 day to prevent look-ahead bias.
#'
#' @return A numeric vector of the cumulative portfolio equity curve.
#' @export
cpp_backtest <- function(asset_returns, signals) {
    .Call('_dataapp_cpp_backtest', PACKAGE = 'dataapp', asset_returns, signals)
}

